import Head from "next/head";
import Layout from "@/components/Layouts/Layout";

const Rent = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>rent</Layout>
    </>
  );
};

export default Rent;
